// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIxXj4EMr2vl-W1X7NpB7qsyrPHWfxwQ',
    appId: '1:536002452385:web:724cd200d8853dbaa309e0',
    messagingSenderId: '536002452385',
    projectId: 'fir-class01-dab97',
    authDomain: 'fir-class01-dab97.firebaseapp.com',
    databaseURL: 'https://fir-class01-dab97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-class01-dab97.appspot.com',
    measurementId: 'G-CF8BMLVT8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM5csbYnqAojZY_yExzRhllVFggaYemg8',
    appId: '1:536002452385:android:262ec67b13dd6a1aa309e0',
    messagingSenderId: '536002452385',
    projectId: 'fir-class01-dab97',
    databaseURL: 'https://fir-class01-dab97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-class01-dab97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjZr-JJcNZdnfN7otFFp0-gw1RszA2y8',
    appId: '1:536002452385:ios:158ffd4cc2c1dfa0a309e0',
    messagingSenderId: '536002452385',
    projectId: 'fir-class01-dab97',
    databaseURL: 'https://fir-class01-dab97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-class01-dab97.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjZr-JJcNZdnfN7otFFp0-gw1RszA2y8',
    appId: '1:536002452385:ios:158ffd4cc2c1dfa0a309e0',
    messagingSenderId: '536002452385',
    projectId: 'fir-class01-dab97',
    databaseURL: 'https://fir-class01-dab97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-class01-dab97.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeIxXj4EMr2vl-W1X7NpB7qsyrPHWfxwQ',
    appId: '1:536002452385:web:1afd5f0944c14058a309e0',
    messagingSenderId: '536002452385',
    projectId: 'fir-class01-dab97',
    authDomain: 'fir-class01-dab97.firebaseapp.com',
    databaseURL: 'https://fir-class01-dab97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-class01-dab97.appspot.com',
    measurementId: 'G-NHBVGXQHM3',
  );
}
